### ISSUE TITLE
Log in CLF

### ISSUE THREAD

**Issue by muety** [muety/kitsquid#14]
Log requests in [common log format](http://publib.boulder.ibm.com/tividd/td/ITWSA/ITWSA_info45/en_US/HTML/guide/c-logs.html#common) to enable for easily analyzing them with tools like [GoAccess](https://goaccess.io/). See https://gin-gonic.com/docs/examples/custom-log-format/.

**Comment by TheodosiouTh** [comment]
Can I take a crack at this issue?

**Comment by muety** [comment]
Yes, please!

**Comment by TheodosiouTh** [comment]
@muety  Could you assign me on the issue since I worked on it?
Also, I added the PR that closes this issue (#15 ) feel free to take a look.
